build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-gcs
    when:
      branch: master

plugin:
  name: Google Cloud Storage
  desc: Publish files and artifacts to Google Cloud Storage
  type: publish
  image: plugins/drone-gcs
  labels:
    - publish
    - artifacts
    - google compute
